# Generated by Django 5.2.7 on 2025-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Doces', 'Doces'), ('Salgados', 'Salgados'), ('Outros', 'Outros')], default='Bebidas', max_length=40)),
                ('descricao', models.TextField(default='Sem descrição', max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='imagens_produtos')),
                ('promocao', models.BooleanField(default=False)),
                ('hora_criacao', models.TimeField(auto_now_add=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
