# Generated by Django 5.2.7 on 2025-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Doces', 'Doces'), ('Salgados', 'Salgados'), ('Outros', 'Outros')], default='Doces', max_length=20)),
                ('descricao', models.TextField(default='Sem descrição', max_length=400)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='Images_products')),
                ('promocao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
