# Generated by Django 5.2.7 on 2025-11-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
