# Generated by Django 5.2.7 on 2025-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp_uploads'),
        ),
    ]
