# Generated by Django 5.2.7 on 2025-11-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_imagem_produto_img_url_produto_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('bebidas', 'bebidas'), ('doces', 'doces'), ('salgados', 'salgados'), ('outros', 'outros')], default='bebidas', max_length=40),
        ),
    ]
